services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000" # Проброс порта
    environment:
      # Переменные для подключения к БД
      - DATABASE_URL=postgresql://user:password@db:5432/expense_db
      # Секретный ключ
      - SECRET_KEY=a_very_secret_key_for_docker
    depends_on:
      - db

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13 # готовый образ PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Сохранение данных БД
    environment:
      - POSTGRES_DB=expense_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: